"""add table ImpresoraEnSitio

Revision ID: 4b4ae682ab7d
Revises: 693e9dda83d3
Create Date: 2025-07-31 16:51:08.794449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import *


# revision identifiers, used by Alembic.
revision: str = "4b4ae682ab7d"
down_revision: Union[str, Sequence[str], None] = "693e9dda83d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pms_impresora_en_sitio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=255), nullable=False),
        sa.Column("a_color", sa.Boolean(), nullable=False),
        sa.Column("impresora_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["impresora_id"],
            ["pms_impresora.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pms_impresora_en_sitio_a_color"),
        "pms_impresora_en_sitio",
        ["a_color"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pms_impresora_en_sitio_id"),
        "pms_impresora_en_sitio",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pms_impresora_en_sitio_impresora_id"),
        "pms_impresora_en_sitio",
        ["impresora_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pms_impresora_en_sitio_ip"),
        "pms_impresora_en_sitio",
        ["ip"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pms_impresora_en_sitio_ip"), table_name="pms_impresora_en_sitio"
    )
    op.drop_index(
        op.f("ix_pms_impresora_en_sitio_impresora_id"),
        table_name="pms_impresora_en_sitio",
    )
    op.drop_index(
        op.f("ix_pms_impresora_en_sitio_id"), table_name="pms_impresora_en_sitio"
    )
    op.drop_index(
        op.f("ix_pms_impresora_en_sitio_a_color"), table_name="pms_impresora_en_sitio"
    )
    op.drop_table("pms_impresora_en_sitio")
    # ### end Alembic commands ###
