"""init

Revision ID: 693e9dda83d3
Revises: 
Create Date: 2025-07-24 17:30:17.221383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import *


# revision identifiers, used by Alembic.
revision: str = '693e9dda83d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pms_impresora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_para_mostrar', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=False),
    sa.Column('cantidad_alquiladas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_impresora_id'), 'pms_impresora', ['id'], unique=False)
    op.create_index(op.f('ix_pms_impresora_nombre'), 'pms_impresora', ['nombre'], unique=False)
    op.create_index(op.f('ix_pms_impresora_nombre_para_mostrar'), 'pms_impresora', ['nombre_para_mostrar'], unique=False)
    op.create_table('pms_suministro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('upc', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('tipo_suministro', sa.String(length=255), nullable=False),
    sa.Column('capacidad_paginas', sa.Integer(), nullable=False),
    sa.Column('productos_compatibles', sa.String(length=255), nullable=False),
    sa.Column('picture_url', sa.String(length=255), nullable=False),
    sa.Column('impresora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impresora_id'], ['pms_impresora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_suministro_id'), 'pms_suministro', ['id'], unique=False)
    op.create_index(op.f('ix_pms_suministro_impresora_id'), 'pms_suministro', ['impresora_id'], unique=False)
    op.create_index(op.f('ix_pms_suministro_nombre'), 'pms_suministro', ['nombre'], unique=False)
    op.create_index(op.f('ix_pms_suministro_productos_compatibles'), 'pms_suministro', ['productos_compatibles'], unique=False)
    op.create_index(op.f('ix_pms_suministro_sku'), 'pms_suministro', ['sku'], unique=False)
    op.create_index(op.f('ix_pms_suministro_tipo_suministro'), 'pms_suministro', ['tipo_suministro'], unique=False)
    op.create_index(op.f('ix_pms_suministro_upc'), 'pms_suministro', ['upc'], unique=False)
    op.create_table('pms_transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suministro_id', sa.Integer(), nullable=False),
    sa.Column('stock_antes', sa.Integer(), nullable=False),
    sa.Column('cantidad_afectada', sa.Integer(), nullable=False),
    sa.Column('stock_despues', sa.Integer(), nullable=False),
    sa.Column('tipo_transaccion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('transaccion_revertida_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suministro_id'], ['pms_suministro.id'], ),
    sa.ForeignKeyConstraint(['transaccion_revertida_id'], ['pms_transaccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pms_transaccion_id'), 'pms_transaccion', ['id'], unique=False)
    op.create_index(op.f('ix_pms_transaccion_tipo_transaccion'), 'pms_transaccion', ['tipo_transaccion'], unique=False)
    op.create_index(op.f('ix_pms_transaccion_transaccion_revertida_id'), 'pms_transaccion', ['transaccion_revertida_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pms_transaccion_transaccion_revertida_id'), table_name='pms_transaccion')
    op.drop_index(op.f('ix_pms_transaccion_tipo_transaccion'), table_name='pms_transaccion')
    op.drop_index(op.f('ix_pms_transaccion_id'), table_name='pms_transaccion')
    op.drop_table('pms_transaccion')
    op.drop_index(op.f('ix_pms_suministro_upc'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_tipo_suministro'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_sku'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_productos_compatibles'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_nombre'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_impresora_id'), table_name='pms_suministro')
    op.drop_index(op.f('ix_pms_suministro_id'), table_name='pms_suministro')
    op.drop_table('pms_suministro')
    op.drop_index(op.f('ix_pms_impresora_nombre_para_mostrar'), table_name='pms_impresora')
    op.drop_index(op.f('ix_pms_impresora_nombre'), table_name='pms_impresora')
    op.drop_index(op.f('ix_pms_impresora_id'), table_name='pms_impresora')
    op.drop_table('pms_impresora')
    # ### end Alembic commands ###
