"""add field nombre to table ImpresoraEnSitio.

Revision ID: a85bb2c8c88f
Revises: 4b4ae682ab7d
Create Date: 2025-08-01 06:16:23.128598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.models import *


# revision identifiers, used by Alembic.
revision: str = 'a85bb2c8c88f'
down_revision: Union[str, Sequence[str], None] = '4b4ae682ab7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pms_impresora_en_sitio', sa.Column('nombre', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pms_impresora_en_sitio', 'nombre')
    # ### end Alembic commands ###
