import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Gauge, Pencil, Plus, Printer, Search, Trash2, Wifi, WifiOff } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { api, json } from '@/lib/api'
import type { Page, Printer as PrinterType, Site } from '@/lib/types'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Field, SelectField } from '@/components/fields'
import { Empty, ErrorState, Loading, PageHeader } from '@/components/common'
import { formatDate } from '@/lib/utils'

function SiteForm({site,onDone}:{site?:Site;onDone:()=>void}){
  const client=useQueryClient();const printers=useQuery({queryKey:['printers'],queryFn:()=>api<PrinterType[]>('/pms/impresoras')})
  const [form,setForm]=useState({nombre:site?.nombre||'',ip:site?.ip||'',a_color:site?.a_color||false,impresora_id:site?.impresora.id||0})
  const save=useMutation({mutationFn:()=>api<Site>(site?`/pms/impresoras-en-sitio/${site.id}`:'/pms/impresoras-en-sitio',json(site?'PUT':'POST',form)),onSuccess:()=>{client.invalidateQueries({queryKey:['sites']});toast.success(site?'Equipo actualizado':'Equipo creado');onDone()},onError:e=>toast.error(e.message)})
  return <form className="grid gap-4" onSubmit={e=>{e.preventDefault();save.mutate()}}><Field label="Nombre o ubicación" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})} required/><Field label="Dirección IP" value={form.ip} inputMode="decimal" onChange={e=>setForm({...form,ip:e.target.value})} required/><SelectField label="Modelo" value={form.impresora_id} onChange={e=>setForm({...form,impresora_id:Number(e.target.value)})} required><option value="">Selecciona un modelo</option>{printers.data?.map(p=><option key={p.id} value={p.id}>{p.nombre_para_mostrar}</option>)}</SelectField><label className="flex min-h-12 items-center gap-3 rounded-xl border border-line bg-surface px-4 text-sm font-semibold text-ink shadow-card"><input type="checkbox" checked={form.a_color} onChange={e=>setForm({...form,a_color:e.target.checked})} className="rounded border-line text-brand focus:ring-brand"/>Impresora a color</label><Button disabled={save.isPending}>{save.isPending?'Guardando…':'Guardar equipo'}</Button></form>
}

function status(site:Site){if(!site.telemetria)return{label:'Sin datos',tone:'neutral' as const,icon:Gauge};if(site.telemetria.obsoleta)return{label:'Sin actualizar',tone:'warn' as const,icon:Gauge};if(!site.telemetria.disponible)return{label:'Sin conexión',tone:'bad' as const,icon:WifiOff};return{label:'En línea',tone:'good' as const,icon:Wifi}}

export function SitesPage(){
  const [q,setQ]=useState('');const[open,setOpen]=useState(false);const sites=useQuery({queryKey:['sites',q],queryFn:()=>api<Page<Site>>(`/pms/impresoras-en-sitio?page_size=100&q=${encodeURIComponent(q)}`)})
  return <><PageHeader eyebrow="Piso de impresión" title="Equipos" description="El último pulso enviado desde la red interna." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="primary" size="icon" aria-label="Nuevo equipo"><Plus/></Button></DialogTrigger><DialogContent><DialogHeader title="Nuevo equipo" description="El colector lo incluirá en su siguiente ciclo."/><SiteForm onDone={()=>setOpen(false)}/></DialogContent></Dialog>}/><label className="relative mb-5 block max-w-xl"><Search className="absolute left-3.5 top-3 text-muted" size={18}/><Input className="pl-11" placeholder="Buscar ubicación o IP" value={q} onChange={e=>setQ(e.target.value)}/></label>
    {sites.isLoading?<Loading/>:sites.data?.items.length?<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{sites.data.items.map(site=>{const state=status(site);const Icon=state.icon;return<Link key={site.id} to={`/equipos/${site.id}`}><Card className="h-full transition hover:-translate-y-0.5 hover:border-brand/40 hover:shadow-lift"><div className="flex items-start justify-between gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-brand-soft text-brand"><Printer/></span><Badge tone={state.tone}><Icon size={13} className="mr-1"/>{state.label}</Badge></div><h2 className="mt-5 text-lg font-bold tracking-tight text-ink">{site.nombre}</h2><p className="text-sm text-muted">{site.impresora.nombre_para_mostrar}</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="font-mono text-xs text-muted">{site.ip}</span><span className="text-xs text-muted">{site.telemetria?formatDate(site.telemetria.observada_en):'Pendiente'}</span></div></Card></Link>})}</div>:<Empty title="No hay equipos" description="Agrega la primera impresora instalada para que el colector pueda consultarla."/>}
  </>
}

function Meter({label,value,color}:{label:string;value:number;color?:string}){return <div><div className="mb-1.5 flex justify-between text-sm"><span className="text-ink">{label}</span><span className="font-mono font-semibold text-ink">{value}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-canvas"><div className="h-full rounded-full transition-all" style={{width:`${Math.max(0,Math.min(100,value))}%`,background:color||'rgb(var(--c-ink))'}}/></div></div>}

// Algunas impresoras reportan un color dos veces (el tóner y su tambor/kit). Se muestra
// uno por color: el de nivel más bajo, que es el consumible que se gasta.
type Toner=NonNullable<Site['telemetria']>['toners'][number]
function tonersUnicos(toners:Toner[]):Toner[]{const porColor=new Map<string,Toner>();for(const t of toners){const clave=t.color||'';const prev=porColor.get(clave);if(!prev||(t.uso??101)<(prev.uso??101))porColor.set(clave,t)}return[...porColor.values()]}

export function SiteDetailPage(){
  const{id}=useParams();const navigate=useNavigate();const client=useQueryClient();const[edit,setEdit]=useState(false)
  const site=useQuery({queryKey:['site',Number(id)],queryFn:()=>api<Site>(`/pms/impresoras-en-sitio/${id}`),refetchInterval:60000})
  const remove=useMutation({mutationFn:()=>api<void>(`/pms/impresoras-en-sitio/${id}`,json('DELETE')),onSuccess:()=>{client.invalidateQueries({queryKey:['sites']});toast.success('Equipo eliminado');navigate('/equipos')},onError:e=>toast.error(e.message)})
  if(site.isLoading)return<Loading/>;if(!site.data)return<ErrorState message={site.error?.message}/>
  const item=site.data;const state=status(item);const telemetry=item.telemetria;const tonerColor=(name?:string)=>({Cyan:'#06b6d4',Magenta:'#db2777',Amarillo:'#f59e0b',Negro:'rgb(var(--c-ink))'}[name||'']||'rgb(var(--c-ink))')
  return <><button onClick={()=>navigate(-1)} className="mb-5 flex min-h-11 items-center gap-2 text-sm font-semibold text-muted transition hover:text-ink"><ArrowLeft size={18}/>Volver</button><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{item.impresora.nombre_para_mostrar} · {item.ip}</p><h1 className="page-title mt-1.5">{item.nombre}</h1><Badge className="mt-3" tone={state.tone}>{state.label}</Badge></div><div className="flex gap-2"><Button variant="secondary" size="icon" onClick={()=>setEdit(true)} aria-label="Editar"><Pencil size={18}/></Button><Button variant="danger" size="icon" aria-label="Eliminar" onClick={()=>{if(confirm('¿Eliminar este equipo?'))remove.mutate()}}><Trash2 size={18}/></Button></div></div>
    {!telemetry?<Empty title="Esperando al colector" description="Este equipo aparecerá con datos después del próximo ciclo del colector local."/>:<div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center justify-between border-b border-line pb-4"><div><p className="eyebrow">Suministros del equipo</p><h2 className="section-title mt-1">Niveles actuales</h2></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-soft text-brand"><Printer size={20}/></span></div><div className="mt-6 grid gap-5">{tonersUnicos(telemetry.toners).map((toner,index)=><Meter key={index} label={`${toner.nombre||'Tóner'} ${toner.color||''}`} value={toner.uso??0} color={tonerColor(toner.color)}/>)}{telemetry.cartucho&&<Meter label={telemetry.cartucho.nombre||'Cartucho'} value={telemetry.cartucho.uso??0}/>} {!telemetry.toners.length&&!telemetry.cartucho&&<p className="text-sm text-muted">El equipo no devolvió niveles de suministros.</p>}</div></Card><div className="grid gap-5"><Card><p className="eyebrow">Contadores</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-canvas p-3"><strong className="font-display text-2xl text-ink sm:text-3xl">{telemetry.consumo?.total_impresiones?.toLocaleString()??'—'}</strong><span className="block text-xs text-muted">Impresiones totales</span></div><div className="rounded-xl bg-canvas p-3"><strong className="font-display text-2xl text-ink sm:text-3xl">{telemetry.consumo?.impresiones_en_color?.toLocaleString()??'—'}</strong><span className="block text-xs text-muted">A color</span></div></div></Card><Card><p className="eyebrow">Identidad</p><dl className="mt-3 grid gap-3 text-sm"><div><dt className="text-muted">Nombre SNMP</dt><dd className="text-ink">{telemetry.nombre_dispositivo||'Sin datos'}</dd></div><div><dt className="text-muted">Serie</dt><dd className="font-mono text-ink">{telemetry.serie||'Sin datos'}</dd></div><div><dt className="text-muted">Última lectura</dt><dd className="text-ink">{formatDate(telemetry.observada_en)}</dd></div></dl></Card></div>{(telemetry.error||telemetry.notificaciones.length>0)&&<Card className="lg:col-span-2"><p className="eyebrow">Avisos del equipo</p><div className="mt-3 grid gap-2">{telemetry.error&&<p className="rounded-xl border border-bad-line bg-bad-soft p-3 text-sm text-bad">{telemetry.error}</p>}{telemetry.notificaciones.map((note,index)=><p key={index} className="rounded-xl border border-line bg-canvas p-3 text-sm text-ink">{note}</p>)}</div></Card>}</div>}
    <Dialog open={edit} onOpenChange={setEdit}><DialogContent><DialogHeader title="Editar equipo"/><SiteForm site={item} onDone={()=>{setEdit(false);site.refetch()}}/></DialogContent></Dialog>
  </>
}
