-- PMS initial schema, ported from app/db/models.py (SQLAlchemy) to Postgres.
-- Spanish domain names and the pms_ table prefix are preserved deliberately.

create table pms_usuario (
    id            integer generated by default as identity primary key,
    username      varchar(80)  not null unique,
    nombre        varchar(160) not null,
    password_hash varchar(255) not null,
    activo        boolean      not null default true,
    creado_en     timestamptz  not null default now()
);
create index ix_pms_usuario_activo on pms_usuario (activo);

create table pms_sesion (
    id         integer generated by default as identity primary key,
    token_hash varchar(64) not null unique,
    usuario_id integer     not null references pms_usuario (id) on delete cascade,
    expira_en  timestamptz not null,
    creado_en  timestamptz not null default now()
);
create index ix_pms_sesion_usuario_id on pms_sesion (usuario_id);
create index ix_pms_sesion_expira_en on pms_sesion (expira_en);

create table pms_impresora (
    id                  integer generated by default as identity primary key,
    nombre              varchar(255) not null,
    nombre_para_mostrar varchar(255) not null,
    picture_url         varchar(500) not null default '',
    cantidad_alquiladas integer      not null default 0
);
create index ix_pms_impresora_nombre on pms_impresora (nombre);
create index ix_pms_impresora_nombre_para_mostrar on pms_impresora (nombre_para_mostrar);

create table pms_impresora_en_sitio (
    id           integer generated by default as identity primary key,
    ip           varchar(255) not null unique,
    nombre       varchar(255) not null unique,
    a_color      boolean      not null default false,
    impresora_id integer      not null references pms_impresora (id)
);
create index ix_pms_impresora_en_sitio_a_color on pms_impresora_en_sitio (a_color);
create index ix_pms_impresora_en_sitio_impresora_id on pms_impresora_en_sitio (impresora_id);

create table pms_suministro (
    id                     integer generated by default as identity primary key,
    nombre                 varchar(255) not null,
    sku                    varchar(255) not null unique,
    upc                    varchar(255) not null unique,
    stock                  integer      not null default 0,
    stock_minimo           integer      not null default 2,
    tipo_suministro        varchar(255) not null,
    capacidad_paginas      integer      not null,
    productos_compatibles  varchar(500) not null,
    picture_url            varchar(500) not null default '',
    impresora_id           integer      not null references pms_impresora (id)
);
create index ix_pms_suministro_nombre on pms_suministro (nombre);
create index ix_pms_suministro_tipo_suministro on pms_suministro (tipo_suministro);
create index ix_pms_suministro_productos_compatibles on pms_suministro (productos_compatibles);
create index ix_pms_suministro_impresora_id on pms_suministro (impresora_id);

create table pms_transaccion (
    id                       integer generated by default as identity primary key,
    suministro_id            integer     not null references pms_suministro (id),
    usuario_id               integer     null     references pms_usuario (id),
    stock_antes              integer     not null,
    cantidad_afectada        integer     not null,
    stock_despues            integer     not null,
    tipo_transaccion         varchar(40) not null,
    fecha                    timestamptz not null default now(),
    transaccion_revertida_id integer     null     references pms_transaccion (id)
);
create index ix_pms_transaccion_suministro_id on pms_transaccion (suministro_id);
create index ix_pms_transaccion_usuario_id on pms_transaccion (usuario_id);
create index ix_pms_transaccion_tipo_transaccion on pms_transaccion (tipo_transaccion);
create index ix_pms_transaccion_fecha on pms_transaccion (fecha);
create index ix_pms_transaccion_revertida_id on pms_transaccion (transaccion_revertida_id);

-- One-to-one latest-snapshot telemetry: overwritten each collector cycle, never appended.
create table pms_telemetria_impresora (
    id                    integer generated by default as identity primary key,
    impresora_en_sitio_id integer      not null unique references pms_impresora_en_sitio (id) on delete cascade,
    observada_en          timestamptz  not null default now(),
    disponible            boolean      not null default false,
    error                 text         null,
    nombre_dispositivo    varchar(255) null,
    serie                 varchar(255) null,
    notificaciones        jsonb        not null default '[]'::jsonb,
    toners                jsonb        not null default '[]'::jsonb,
    cartucho              jsonb        null,
    consumo               jsonb        null
);
create index ix_pms_telemetria_impresora_observada_en on pms_telemetria_impresora (observada_en);
create index ix_pms_telemetria_impresora_disponible on pms_telemetria_impresora (disponible);

-- PostgREST auto-exposes every public table at /rest/v1. These tables are reached only
-- through the API (service_role, which bypasses RLS), so enable RLS with zero policies:
-- that denies anon and authenticated outright.
alter table pms_usuario              enable row level security;
alter table pms_sesion               enable row level security;
alter table pms_impresora            enable row level security;
alter table pms_impresora_en_sitio   enable row level security;
alter table pms_suministro           enable row level security;
alter table pms_transaccion          enable row level security;
alter table pms_telemetria_impresora enable row level security;
